### ISSUE TITLE
Add GH action for integration tests

### ISSUE THREAD

**Issue by matejvasek** [boson-project/func#138]
We should have integrations tests for our binary.

Such a test would try:
create a function
build the function
list functions (the created function should be in the list)
describe the function
deploy the function into cluster
call the function

this should be done for all templates (runtimes/triggers).

**Comment by matejvasek** [comment]
for this the action will have to set up cluster with `KServing` (and maybe `KEventing`).
https://github.com/matzew/kn-box w

**Comment by zroubalik** [comment]
I'd vote for reusing libs/concepts from `kn`: https://github.com/knative/client/blob/master/test`

**Comment by lkingland** [comment]
Unless anyone else feels uniquely qualified, or especially passionate, I'll take a look at this one.

**Comment by lance** [comment]
@lkingland I've been a bit out of the loop lately so just wanted to check in on this to see if any progress has been made. Thx

**Comment by lkingland** [comment]
@lance Yes there's progress being made on this.  Thanks for checking in.  It's not complete, but I can fire up a PR with what's available

**Comment by lance** [comment]
Hey @lkingland - I was speaking with @pmorie yesterday about some work that he's been doing for the larger picture in the serverless universe. If you can push what you've got to a branch, it would be a great help in trying to ensure that whatever we do here fits within the bigger picture. Even if you don't want to push a PR yet, it'd be great to collaborate on a branch.

**Comment by lkingland** [comment]
Sure thing @lance I am working on the WIP PR now.  There's some caviats which I will mention in Slack chat.  Basically flakiness in the underlying system puts us between two bad choices when trying to automate the service creation/removal.  Your input on which bad option to choose will be appreciated.

**Comment by lkingland** [comment]
Hey @lance; That PR now demonstrates firing up a KinD cluster to run tests tagged `integration` for PRs. 

While regular unit tests are run with `make test` (aka `go test`), integration tests are run with `make integration-test` (aka `go test -tags integration`).

This of course requires a local connection to a cluster which is set up and configured for Functions (Knative, Kourier, and various settings).  This can also be accomplished _locally_ by running `make cluster`  (aka `allocate.sh && configure.sh`).  This  sets up and configures a cluster which is then used for the tests, and which can then be removed using `hack/delete.sh`.

Intermediary containers are not sent to quay.io or docker, because that seemed messy and laggy; so a local container registry is also set up and connected to the cluster's network.  This registry is also cleaned up using `delete.sh`.

I'm working on making the integration tests themselves a little bit more thorough before remoiving the "Draft" status of the PR and submitting for review, but it might be worth taking a look at the PR.  I'd be happy to get feedback, and to know this doesn't impinge on anything @pmorie is doing!
