### ISSUE TITLE
Changing the state of a deployed function with kn CLI causes subsequent deployments to fail

### ISSUE THREAD

**Issue by lance** [boson-project/func#270]
Using the kn service update command to change the state of an environment variable after deploying the function causes 'func deploy' to subsequently fail after later code changes.

Deploying function to the cluster results in the following error:

```
Error: knative deployer failed to update the service: giving up after 3 retries: admission webhook "validation.webhook.serving.knative.dev" denied the request: validation failed: Saw the following changes without a name change (-old +new): spec.template.metadata.name
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Image:
	-: "quay.io/ilawson/battleships_win@sha256:d84e62776b884e3b0050f7ab0454a8a56373a8b9f1fa3c7bc89f29c9dbad5c1b"
	+: "quay.io/ilawson/battleships_win@sha256:6fe85cdbfe413df4172caa33983dbdee2beb8af4cffc610c5fd4a80c597c9432"
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Env[0].Value:
	-: "20210225T152647"
	+: "20210301T134645"
{*v1.RevisionTemplateSpec}.Spec.PodSpec.Containers[0].Env[1].Value:
	-: "http://watchman-battleships-backend.apps.summit-dev-aws.m7o7.p1.openshiftapps.com/watch"
	+: "http://watchman-jsonquarkussandbox.apps.summit-dev-21.k9pw.p1.openshiftapps.com/watch"
```

According to @markusthommes the error is caused by generating a new revision name in the client during kn service update.

Related: https://github.com/knative/client/issues/994
Related: https://github.com/knative/client/pull/1240

**Comment by matejvasek** [comment]
I see @rhuss resolved this for `kn`. Shouldn't just updating our `kn` dependency help?

**Comment by matejvasek** [comment]
I stumbled on BYO revison once too https://knative.slack.com/archives/C9JP909F0/p1600876741003800

**Comment by matejvasek** [comment]
Now I see you have trouble with `kn` not `func`. Why is this here.

**Comment by matejvasek** [comment]
Back then we also used client-side generated revision, but it has been removed d5839ea6c1e84e843ad643cc0611a82e2e6d2399.

**Comment by lance** [comment]
> Now I see you have trouble with kn not func. Why is this here.

The issue as I understand it is that if a function is updated via `kn` then later updated with `kn func deploy` the latter fails.

**Comment by zroubalik** [comment]
What if we try to patch the Service instead of update?

**Comment by rhuss** [comment]
The issue is that kn by default uses BYO revision naming until kn 0.21. This means, that for every update that you do via the API you have to also change the revision name in the template (kn does this automatically when in this mode and using `kn service update`. 

I suggest that you explicitly choose server-side revision naming when creating the service. When you could point me to the spot where the service is created, I can check out what to change to make this happen.

**Comment by rhuss** [comment]
> What if we try to patch the Service instead of update?

Patching will lead to the same error. There are tons of issue with this default behaviour, therefor we changed the default in 0.21 (which will probably translate to OSS 1.15). It was only introduced by Naomi for some corner cases AFAIR, where the client needs to know the revision name in advance. This corner case is so obscure though, I don't even remember it 😬 . BYO revision has tons of issue, so I definitely recommend to not use it.

**Comment by utherp0** [comment]
Use case for this is functions that use ENV - I inject config information into the function using an ENV that is defined in the func.yaml; post installation I then update the ENV using 'kn update' and then subsequently I need to *delete* the function before redeploying it (for a code change); this will be a problem for devs....

**Comment by zroubalik** [comment]
@rhuss https://github.com/boson-project/func/blob/38fd673fdbef1094558b32910a42fcdff2d8bb0c/knative/deployer.go#L122

**Comment by rhuss** [comment]
ok, so the generation of the service does not set the revision name, so it must be the update. let me check that, too ...

**Comment by rhuss** [comment]
@zroubalik could you try to set `service.Spec.Template.Name` to an empty string in https://github.com/boson-project/func/blob/38fd673fdbef1094558b32910a42fcdff2d8bb0c/knative/deployer.go#L160 ?

If you update a service and when you are using server-side generated names you always need to remove the name so that the server can fill it in with its generated name. Otherwise it will think that you want to set the name and because the name already exists from the original service, it rejects the update.

**Comment by zroubalik** [comment]
@rhuss I'll give it a try

**Comment by zroubalik** [comment]
The suggested fix is working for me, thanks @rhuss !
