### ISSUE TITLE
Function name should match service name

### ISSUE THREAD

**Issue by lance** [boson-project/func#276]
At the moment, the function name almost always matches the service name. However, if the function name has a dash in it, the service name gets a double dash. E.g. a function named `game-score` becomes a service named `game--score`, which is not ideal.

**Comment by rhuss** [comment]
I remember a long discussion with @lkingland about what is more important: The external URL or that the KService and the Function share the same identity (aka name). (unfortunately, I lost the link to this discussion along with the reasoning that it contained)

My POV is still that you can't treat the KService as an implementation detail that is completely hidden by the user if we are leveraging func as a plugin of `kn` which is for Knative and from which commands are shared to e.g. examine KService created for functions. I have strong feelings here ;-)

But it's not only me since I heard quite some feedback from people who were equally surprised about this kind of name encoding and that you can't map a function name 1:1 to a Knative service name.

**Comment by lkingland** [comment]
As a developer, I would like to "create www.example.org" and "create www.example.com" using Functions, and serve them both from the same cluster.  They should also be SSL secured via the configured cluster issuer.   Here is a demo of this workflow working (no vaporware):  https://lukekingland.com/vid/standard-handler.mp4
We have backed off this workflow a bit since then.  I am interested to know if there is a technical solution we can offer that both provides this level of abstraction while still maintaining a 1:1 relationship between the function names and their underlying service name.  It is my understanding that the limitation is in Kubernetes itself, not Knative.  Perhaps the recent work done to enable Service domain names would help here (which was not used for the demo video above).

**Comment by rhuss** [comment]
+1 for option 2, I think it's fair to apply this restriction on naming which still allows enough choice for the naming.

**Comment by lance** [comment]
> I prefer solution 2. as it is more straightforward and doesn't do any unexpected conversion, it is more opinionated (wrt function naming) though

I think opinionated is often the right approach. I'm +1 for #2.

**Comment by lkingland** [comment]
If we make this change, we will be unable to run the following commands:
`create myapp.boson-project.org`
`create myapp.boson-project.com`
This use-case was fully working before (see [the demo](https://lukekingland.com/vid/standard-handler.mp4) above), and I feel like it is an important pattern.  If we are going to go ahead and agree that it is not a valuable use-case, that's fine, but how will we do this now?  Perhaps:
`create myappOrg --route myapp.boson-project.org`
`create myappCom --route myapp.boson-project.com`
I am having a hard time not feeling like this is a step backwards in usability, but perhaps there is a better way?

**Comment by rhuss** [comment]
Wouldn't it be good enough to create an opinionated URL and show that at the end, but allow the user to overwrite the URL if needed ? So I don't think that the second suggestion with the `--route` option is bad at all (and gives the user 2 degrees of freedom (service name not coupled to final URL, but having good default).

The difference is that the route URL will be auto-generated by default instead of the service name (that is needed to identify the function in other management calls with `kn`), but you still have the freedom to chose both independently. To iterate on my main argument to use the service name as an identifier and being identical to the function name is, that many other commands of `kn` use the service name (not the function name) as the identifier (like listing services, deleting services, connecting services to the event infrastructure, ....). If the service and function name differs and is not considered to be equivalent, then this is totally confusing to the user. 

The alternative to the invariant  **service name == function name** would be to decouple `func` from `kn` and offer all the service and eventing commands also on `func`, including the translation from func name to service name. But I don't think this is a good and feasible solution.

**Comment by zroubalik** [comment]
Agree with Roland on this.

And I as well think, that an option like `--route` is a great one. As an extra it gives user ability to update the route without changing the function name (as it would have to happen if we go with the function name == route).
